### ISSUE TITLE
Ojo con referencias a dominios

### ISSUE THREAD

**Issue by julianbutti** [eliasagustin/gestionVacantes#1]
https://github.com/eliasagustin/gestionVacantes/blob/41dacb1a5a0445e60168cc32d265b5f839e023ab/vistas/vacante_detallada.php#L169C58-L169C90

Te conviene usar PHP_SELF, o alguna posicion del $_SERVER que haga referencia al dominio actual y no hardcodearlo. Para que te funcione en local y en cualquier dominio que tengas

**Comment by eliasagustin** [comment]
solucionado usando el problema de la referencia al dominio actual y no hardcodearla
$_SERVER['PHP_HOST']
