### ISSUE TITLE
Ojo con dejar claves hardcodeadas en el código en diferentes lugares, fijate el uso de dotenv para php

### ISSUE THREAD

**Issue by julianbutti** [eliasagustin/gestionVacantes#2]
https://github.com/eliasagustin/gestionVacantes/blob/41dacb1a5a0445e60168cc32d265b5f839e023ab/php/main.php#L8

**Comment by eliasagustin** [comment]
muy buena herramienta, no la conocía ... habrá una forma de utilizarla sin instalar el composer? ... por las dudas la clave hardcodeada solo se encuentra en el main y de ahi va llamando a la función para lograr la conexión cuando se necesario.

**Comment by eliasagustin** [comment]
Ahora si para cumplir con el requisito logré:
- instalación de composer
- luego el dotenv
- cree el archivo .env (con las variables de la bd) 

luego dentro del main que ejecuta la conexión cambié sus parametros para llamarlos
	
# Conexion a la base de datos #
function conexion(){
		$mysqli = new mysqli($_ENV["DATABASE_HOSTNAME"],$_ENV["DATABASE_USERNAME"],$_ENV["DATABASE_PASSWORD"],$_ENV["DATABASE_NAME"]);
		return $mysqli;
	}
